spring:
  application:
    name: Capstone

  profiles:
    active: db, key

  jackson:
    deserialization:
      fail-on-unknown-properties: false

server:
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
    try-it-out-enabled: ${SPRINGDOC_SWAGGER_UI_TRY_IT_OUT_ENABLED:true}
    operations-sorter: method
    tags-sorter: alpha
    filter: true
  paths-to-match: /**
